[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  
[functions."health"]
  runtime = "python3.9"

[functions."sync_order"]
  runtime = "python3.9"

[[redirects]]
  from = "/api/sync-order"
  to = "/.netlify/functions/sync_order"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
